<!-- Facebook Pixel Code -->
<script type="text/javascript">
//<![CDATA[
    !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
        n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
        document,'script','//connect.facebook.net/<?php echo $this->getLocale() ?>/fbevents.js');
    // Insert Your Facebook Pixel ID below.
    fbq('init', '<?php echo $this->getPixelId() ?>');
    fbq('track', 'PageView');
//]]>
</script>
<!-- Insert Your Facebook Pixel ID below. -->
<noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=<?php echo $this->getPixelId() ?>&amp;ev=PageView&amp;noscript=1" /></noscript>
<!-- End Facebook Pixel Code -->
<script type="text/x-magento-init">
{
    "*": {
        "Peec_Facebook/js/pixel": {}
    }
}
</script>
