<?php
$width = trim($this->getWidth());
?>
<div class="fb-like"
     data-href="<?php echo $this->getUrlInterface()->getCurrentUrl(); ?>"
     data-layout="<?php echo $this->getProductLayout() ?>"
     data-action="<?php echo $this->getAction() ?>"
     data-colorscheme="<?php echo $this->getColorScheme() ?>"
     data-share="<?php echo $this->getShare() === "1" ? "true" : "false" ?>"
     data-show-faces="<?php echo $this->getShowFaces() === "1" ? "true" : "false" ?>"
    <?php if ($width): ?>
        data-width="<?php echo $width?>"
    <?php endif?>
    >
</div>